# ADOBE CONFIDENTIAL
#
# Copyright 2020 Adobe
# All Rights Reserved.
#
# NOTICE:  Adobe permits you to use, modify, and distribute this file in
# accordance with the terms of the Adobe license agreement accompanying it.
# If you have received this file from a source other than Adobe,
# then your use, modification, or distribution of it requires the prior
# written permission of Adobe.
#
# Autogenerated by ipa. Don't edit directly, edit the definitions and regenerate it when changing
#

import ctypes
import base64
from .sdarray import *
from .sdvaluestring import *
from .sdapiobject import *
from .sdapiobject import *
from .apiexception import APIException

class SDColorManagementEngine(SDAPIObject):
    """
    Color management engine. There is only one SDColorManagementEngine, that you can retrieve from the SDApplication
    """
    def __init__(self, APIContext, handle, *args, **kwargs):
        """
        Constructor

        :rtype: SDColorManagementEngine
        """
        SDAPIObject.__init__(self, APIContext, handle, *args, **kwargs)

    def getName(self):
        """
        Get the color management engine name

        :rtype: string
        """
        outValue = ctypes.c_char_p()
        _res = self.mAPIContext.SDColorManagementEngine_getName(self.mHandle, ctypes.byref(outValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return outValue.value.decode('utf-8')

    def getWorkingColorSpaceName(self):
        """
        Get the working color space name

        :rtype: string
        """
        outValue = ctypes.c_char_p()
        _res = self.mAPIContext.SDColorManagementEngine_getWorkingColorSpaceName(self.mHandle, ctypes.byref(outValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return outValue.value.decode('utf-8')

    def getRawColorSpaceName(self):
        """
        Get the raw color space name

        :rtype: string
        """
        outValue = ctypes.c_char_p()
        _res = self.mAPIContext.SDColorManagementEngine_getRawColorSpaceName(self.mHandle, ctypes.byref(outValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return outValue.value.decode('utf-8')

    def getColorSpaces(self):
        """
        Get the list of color space names.

        :rtype: SDArray[SDValueString]
        """
        outColorSpaceArray = ctypes.c_void_p()
        _res = self.mAPIContext.SDColorManagementEngine_getColorSpaces(self.mHandle, ctypes.byref(outColorSpaceArray))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outColorSpaceArray, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outColorSpaceArray.value, ownHandle=True)

    def getOCIOConfigFileName(self):
        """
        Get the filename of the current OCIO configuration or None, if not using OpenColorIO

        :rtype: string
        """
        outValue = ctypes.c_char_p()
        _res = self.mAPIContext.SDColorManagementEngine_getOCIOConfigFileName(self.mHandle, ctypes.byref(outValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return outValue.value.decode('utf-8')

