# ADOBE CONFIDENTIAL
#
# Copyright 2020 Adobe
# All Rights Reserved.
#
# NOTICE:  Adobe permits you to use, modify, and distribute this file in
# accordance with the terms of the Adobe license agreement accompanying it.
# If you have received this file from a source other than Adobe,
# then your use, modification, or distribution of it requires the prior
# written permission of Adobe.
#
# Autogenerated by ipa. Don't edit directly, edit the definitions and regenerate it when changing
#

import ctypes
import base64
import sd
from .sddefinition import *
from .sdtype import *
from .sdapiobject import *
from .sdtype import *
from .sdapiobject import *
from .apiexception import APIException

class SDGraphDefinition(SDAPIObject):
    """
    A SDGraphDefinition contains information about a graph type in SD
    """
    def __init__(self, APIContext, handle, *args, **kwargs):
        """
        Constructor

        :rtype: SDGraphDefinition
        """
        SDAPIObject.__init__(self, APIContext, handle, *args, **kwargs)

    @staticmethod
    def sNew(id):
        """
        Create new SDTypeVoid

        :param id: The id of the SDGraphDefinition. It has to be unique in the application.
        :type id: string
        :rtype: SDGraphDefinition
        """
        outSDGraphDefinition = ctypes.c_void_p()
        _res = sd.getContext().SDGraphDefinition_sNew(ctypes.create_string_buffer(id.encode('utf-8')), ctypes.byref(outSDGraphDefinition))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = sd.getContext().mTypeMap[SDAPIObject(sd.getContext(), outSDGraphDefinition, ownHandle=False).getClassName()]
        return constructor(sd.getContext(), outSDGraphDefinition.value, ownHandle=True)

    def getId(self):
        """
        Get the identifier of the graph definition

        :rtype: string
        """
        outId = ctypes.c_char_p()
        _res = self.mAPIContext.SDGraphDefinition_getId(self.mHandle, ctypes.byref(outId))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return outId.value.decode('utf-8')

    def addDefinition(self, sdDefinition):
        """
        Add the definition the graph definition will support

        :param sdDefinition: The node definition to add
        :type sdDefinition: SDDefinition
        :rtype: None
        """
        _res = self.mAPIContext.SDGraphDefinition_addDefinition(self.mHandle, sdDefinition.mHandle)
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return None

    def removeDefinition(self, sdDefinition):
        """
        Remove the specified definition from the graph definition

        :param sdDefinition: The node definition to remove
        :type sdDefinition: SDDefinition
        :rtype: None
        """
        _res = self.mAPIContext.SDGraphDefinition_removeDefinition(self.mHandle, sdDefinition.mHandle)
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return None

    def getDefinitionFromId(self, id):
        """
        Get the SDDefinition that match the specified Id

        :param id: The id of the SDDefinition to retrieve
        :type id: string
        :rtype: SDDefinition
        """
        outSDDefinition = ctypes.c_void_p()
        _res = self.mAPIContext.SDGraphDefinition_getDefinitionFromId(self.mHandle, ctypes.create_string_buffer(id.encode('utf-8')), ctypes.byref(outSDDefinition))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDDefinition, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDDefinition.value, ownHandle=True)

    def addType(self, sdType):
        """
        Add the type the graph definition will support

        :param sdType: The type to add
        :type sdType: SDType
        :rtype: None
        """
        _res = self.mAPIContext.SDGraphDefinition_addType(self.mHandle, sdType.mHandle)
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return None

    def setLabel(self, label):
        """
        Set the label of the graph definition

        :param label: The label of the graph definition
        :type label: string
        :rtype: None
        """
        _res = self.mAPIContext.SDGraphDefinition_setLabel(self.mHandle, ctypes.create_string_buffer(label.encode('utf-8')))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return None

    def setIconFile(self, iconFilePath):
        """
        Set the icon of the graph definition from the specified file

        :param iconFilePath: The file of the icon
        :type iconFilePath: string
        :rtype: None
        """
        _res = self.mAPIContext.SDGraphDefinition_setIconFile(self.mHandle, ctypes.create_string_buffer(iconFilePath.encode('utf-8')))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return None

