# ADOBE CONFIDENTIAL
#
# Copyright 2020 Adobe
# All Rights Reserved.
#
# NOTICE:  Adobe permits you to use, modify, and distribute this file in
# accordance with the terms of the Adobe license agreement accompanying it.
# If you have received this file from a source other than Adobe,
# then your use, modification, or distribution of it requires the prior
# written permission of Adobe.
#
# Autogenerated by ipa. Don't edit directly, edit the definitions and regenerate it when changing
#

import ctypes
import base64
import sd
from enum import Enum
from .sdtype import *
from .sdarray import *
from .sdproperty import *
from .sdvalue import *
from .sdmetadatadict import *
from .sdapiobject import *
from .sdpackage import *
from .sdtype import *
from .sdproperty import *
from .sdproperty import *
from .sdapiobject import *
from .apiexception import APIException

class EmbedMethod(Enum):
    """
    Enum representing the embedding method for resources when using external assets
    """
    Undefined = 0
    """The resource references its original file"""
    Linked = 1
    """The original file is copied to another location, and the resource references the copy."""
    CopiedAndLinked = 2
    """The file content is encoded directly in the resource (in memory at runtime, and in the Package file content). No file is referenced."""
    BinaryEmbedded = 3

class SDResource(SDAPIObject):
    """
    Class managing any element that can be part of a SDPackage (Graph, Bitmap, Folder, ...)
    """
    def __init__(self, APIContext, handle, *args, **kwargs):
        """
        Constructor

        :rtype: SDResource
        """
        SDAPIObject.__init__(self, APIContext, handle, *args, **kwargs)

    def getType(self):
        """
        Get the resource type as SDType

        :rtype: SDType
        """
        outType = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getType(self.mHandle, ctypes.byref(outType))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outType, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outType.value, ownHandle=True)

    def getIdentifier(self):
        """
        Get the resource identifier as string

        :rtype: string
        """
        outIdentifier = ctypes.c_char_p()
        _res = self.mAPIContext.SDResource_getIdentifier(self.mHandle, ctypes.byref(outIdentifier))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return outIdentifier.value.decode('utf-8')

    def setIdentifier(self, identifier):
        """
        Set the resource identifier

        :param identifier: The new resource identifier
        :type identifier: string
        :rtype: None
        """
        _res = self.mAPIContext.SDResource_setIdentifier(self.mHandle, ctypes.create_string_buffer(identifier.encode('utf-8')))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return None

    def getUrl(self):
        """
        Retrieve the resource URL

        :rtype: string
        """
        outUrl = ctypes.c_char_p()
        _res = self.mAPIContext.SDResource_getUrl(self.mHandle, ctypes.byref(outUrl))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return outUrl.value.decode('utf-8')

    def getFilePath(self):
        """
        Get the path of the file used by this resource

        :rtype: string
        """
        outPath = ctypes.c_char_p()
        _res = self.mAPIContext.SDResource_getFilePath(self.mHandle, ctypes.byref(outPath))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return outPath.value.decode('utf-8')

    def getEmbedMethod(self):
        """
        Get the method used by this resource to reference its content or file (See EmbedMethod enum)

        :rtype: EmbedMethod
        """
        outEmbedMethod = ctypes.c_int()
        _res = self.mAPIContext.SDResource_getEmbedMethod(self.mHandle, ctypes.byref(outEmbedMethod))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return EmbedMethod(outEmbedMethod.value)

    def getProperties(self, sdPropertyCategory):
        """
        Get all properties of the specified category (Input, Output or Annotation)

        :param sdPropertyCategory: The enum value the indicate which type of properties to get
        :type sdPropertyCategory: SDPropertyCategory
        :rtype: SDArray[SDProperty]
        """
        outSDPropertyArray = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getProperties(self.mHandle, sdPropertyCategory.value, ctypes.byref(outSDPropertyArray))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDPropertyArray, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDPropertyArray.value, ownHandle=True)

    def getPropertyFromId(self, sdPropertyId, sdPropertyCategory):
        """
        Get property that match the specified identifier in the specified category

        :param sdPropertyId: The identifier of the property we want to retrieve
        :type sdPropertyId: string
        :param sdPropertyCategory: The category of the property
        :type sdPropertyCategory: SDPropertyCategory
        :rtype: SDProperty
        """
        outSDProperty = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getPropertyFromId(self.mHandle, ctypes.create_string_buffer(sdPropertyId.encode('utf-8')), sdPropertyCategory.value, ctypes.byref(outSDProperty))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDProperty, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDProperty.value, ownHandle=True)

    def getPropertyValue(self, sdProperty):
        """
        Get the value of a property

        :param sdProperty: The property we want to retrieve the value from
        :type sdProperty: SDProperty
        :rtype: SDValue
        """
        outSDValue = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getPropertyValue(self.mHandle, sdProperty.mHandle, ctypes.byref(outSDValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDValue, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDValue.value, ownHandle=True)

    def setPropertyValue(self, sdProperty, sdValue):
        """
        Set the value of the specified property

        :param sdProperty: The property we want to retrieve the value from
        :type sdProperty: SDProperty
        :param sdValue: The value to set
        :type sdValue: SDValue
        :rtype: None
        """
        _res = self.mAPIContext.SDResource_setPropertyValue(self.mHandle, sdProperty.mHandle, sdValue.mHandle)
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return None

    def setInputPropertyValueFromId(self, sdInputPropertyId, sdValue):
        """
        Set the value of the specified input property retrieved by his identifier

        :param sdInputPropertyId: The identifier of the input property
        :type sdInputPropertyId: string
        :param sdValue: The value to set
        :type sdValue: SDValue
        :rtype: None
        """
        _res = self.mAPIContext.SDResource_setInputPropertyValueFromId(self.mHandle, ctypes.create_string_buffer(sdInputPropertyId.encode('utf-8')), sdValue.mHandle)
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return None

    def setAnnotationPropertyValueFromId(self, sdAnnotationPropertyId, sdValue):
        """
        Set the value of the specified annotation property retrieved by his identifier

        :param sdAnnotationPropertyId: The identifier of the annotation property
        :type sdAnnotationPropertyId: string
        :param sdValue: The value to set
        :type sdValue: SDValue
        :rtype: None
        """
        _res = self.mAPIContext.SDResource_setAnnotationPropertyValueFromId(self.mHandle, ctypes.create_string_buffer(sdAnnotationPropertyId.encode('utf-8')), sdValue.mHandle)
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return None

    def getPropertyValueFromId(self, sdPropertyId, sdPropertyCategory):
        """
        Get the value of the property that matches the specified identifier in the specified category

        :param sdPropertyId: The identifier of the property we want to retrieve
        :type sdPropertyId: string
        :param sdPropertyCategory: The category of the property
        :type sdPropertyCategory: SDPropertyCategory
        :rtype: SDValue
        """
        outSDValue = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getPropertyValueFromId(self.mHandle, ctypes.create_string_buffer(sdPropertyId.encode('utf-8')), sdPropertyCategory.value, ctypes.byref(outSDValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDValue, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDValue.value, ownHandle=True)

    def getInputPropertyValueFromId(self, sdPropertyId):
        """
        Get the value of the input property that matches the specified identifier

        :param sdPropertyId: The identifier of the input property we want to retrieve
        :type sdPropertyId: string
        :rtype: SDValue
        """
        outSDValue = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getInputPropertyValueFromId(self.mHandle, ctypes.create_string_buffer(sdPropertyId.encode('utf-8')), ctypes.byref(outSDValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDValue, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDValue.value, ownHandle=True)

    def getAnnotationPropertyValueFromId(self, sdPropertyId):
        """
        Get the value of the annotation property that matches the specified identifier

        :param sdPropertyId: The identifier of the annotation property we want to retrieve
        :type sdPropertyId: string
        :rtype: SDValue
        """
        outSDValue = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getAnnotationPropertyValueFromId(self.mHandle, ctypes.create_string_buffer(sdPropertyId.encode('utf-8')), ctypes.byref(outSDValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDValue, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDValue.value, ownHandle=True)

    def getPropertyAnnotations(self, sdProperty):
        """
        Get the annotation properties of the specified property

        :param sdProperty: The SDProperty to retrieve the annotations from
        :type sdProperty: SDProperty
        :rtype: SDArray[SDProperty]
        """
        outSDPropertyArray = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getPropertyAnnotations(self.mHandle, sdProperty.mHandle, ctypes.byref(outSDPropertyArray))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDPropertyArray, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDPropertyArray.value, ownHandle=True)

    def getPropertyAnnotationValueFromId(self, sdProperty, sdPropertyAnnotationId):
        """
        Get the property annotation value of the specified property

        :param sdProperty: The property we want to retrieve the annotation value from
        :type sdProperty: SDProperty
        :param sdPropertyAnnotationId: The identifier of the annotation to retrieve
        :type sdPropertyAnnotationId: string
        :rtype: SDValue
        """
        outSDValue = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getPropertyAnnotationValueFromId(self.mHandle, sdProperty.mHandle, ctypes.create_string_buffer(sdPropertyAnnotationId.encode('utf-8')), ctypes.byref(outSDValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDValue, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDValue.value, ownHandle=True)

    def setPropertyAnnotationValueFromId(self, sdProperty, sdPropertyAnnotationId, sdValue):
        """
        Set the property annotation value of the specified property

        :param sdProperty: The property whose we want to change the annotation value
        :type sdProperty: SDProperty
        :param sdPropertyAnnotationId: The identifier of the annotation to set
        :type sdPropertyAnnotationId: string
        :param sdValue: The SDValue to set
        :type sdValue: SDValue
        :rtype: None
        """
        _res = self.mAPIContext.SDResource_setPropertyAnnotationValueFromId(self.mHandle, sdProperty.mHandle, ctypes.create_string_buffer(sdPropertyAnnotationId.encode('utf-8')), sdValue.mHandle)
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return None

    def getPropertyMetadataDictFromId(self, sdPropertyId, sdPropertyCategory):
        """
        Get the metadata of the property that matches the specified identifier in the specified category as a SDMetadataDict.

        :param sdPropertyId: The identifier of the property we want to retrieve
        :type sdPropertyId: string
        :param sdPropertyCategory: The category of the property
        :type sdPropertyCategory: SDPropertyCategory
        :rtype: SDMetadataDict
        """
        outSDMetadataDict = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getPropertyMetadataDictFromId(self.mHandle, ctypes.create_string_buffer(sdPropertyId.encode('utf-8')), sdPropertyCategory.value, ctypes.byref(outSDMetadataDict))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDMetadataDict, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDMetadataDict.value, ownHandle=True)

    def newProperty(self, sdPropertyId, sdPropertyType, sdPropertyCategory):
        """
        Create a new SDProperty of the specified type and in the specified SDPropertyCategory

        :param sdPropertyId: The identifier of the new property
        :type sdPropertyId: string
        :param sdPropertyType: The type of the new property
        :type sdPropertyType: SDType
        :param sdPropertyCategory: The SDPropertyCategory of the new property to create
        :type sdPropertyCategory: SDPropertyCategory
        :rtype: SDProperty
        """
        outSDProperty = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_newProperty(self.mHandle, ctypes.create_string_buffer(sdPropertyId.encode('utf-8')), sdPropertyType.mHandle, sdPropertyCategory.value, ctypes.byref(outSDProperty))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDProperty, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDProperty.value, ownHandle=True)

    def deleteProperty(self, sdProperty):
        """
        Delete the specified SDProperty

        :param sdProperty: The property to delete
        :type sdProperty: SDProperty
        :rtype: None
        """
        _res = self.mAPIContext.SDResource_deleteProperty(self.mHandle, sdProperty.mHandle)
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return None

    @staticmethod
    def sNewFromFile(parent, filePath, embedMethod):
        """
        Create a new SDResource from the specified file. The resource may reference or copy the file content depending on the EmbedMethod

        :param parent: The parent data that will contains the newly created resource. Can be SDPackage or SDResourceFolder
        :type parent: SDAPIObject
        :param filePath: The file path
        :type filePath: string
        :param embedMethod: The embed method
        :type embedMethod: EmbedMethod
        :rtype: SDResource
        """
        outResource = ctypes.c_void_p()
        _res = sd.getContext().SDResource_sNewFromFile(parent.mHandle, ctypes.create_string_buffer(filePath.encode('utf-8')), embedMethod.value, ctypes.byref(outResource))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = sd.getContext().mTypeMap[SDAPIObject(sd.getContext(), outResource, ownHandle=False).getClassName()]
        return constructor(sd.getContext(), outResource.value, ownHandle=True)

    def getPackage(self):
        """
        Get the SDPackage the current SDResource belongs to.

        :rtype: SDPackage
        """
        outSDPackage = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getPackage(self.mHandle, ctypes.byref(outSDPackage))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDPackage, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDPackage.value, ownHandle=True)

    def getMetadataDict(self):
        """
        Get the metadata of this resource as a SDMetadataDict.

        :rtype: SDMetadataDict
        """
        outSDMetadataDict = ctypes.c_void_p()
        _res = self.mAPIContext.SDResource_getMetadataDict(self.mHandle, ctypes.byref(outSDMetadataDict))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outSDMetadataDict, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outSDMetadataDict.value, ownHandle=True)

