# ADOBE CONFIDENTIAL
#
# Copyright 2020 Adobe
# All Rights Reserved.
#
# NOTICE:  Adobe permits you to use, modify, and distribute this file in
# accordance with the terms of the Adobe license agreement accompanying it.
# If you have received this file from a source other than Adobe,
# then your use, modification, or distribution of it requires the prior
# written permission of Adobe.
#
# Autogenerated by ipa. Don't edit directly, edit the definitions and regenerate it when changing
#

import ctypes
import base64
import sd
from .sdarray import SDArray
from .sdproperty import SDProperty
from .sdtype import SDType
from .sdapiobject import SDAPIObject
from .sdproperty import SDPropertyCategory
from .sdproperty import SDPropertyInheritanceMethod
from .sdtype import SDTypeModifier
from .sdapiobject import SDApiError
from .apiexception import APIException

class SDTypeEnum(SDType):
    """
    Class used to store information about an enumeration type
    """
    def __init__(self, APIContext, handle, *args, **kwargs):
        """
        Constructor

        :rtype: SDTypeEnum
        """
        SDType.__init__(self, APIContext, handle, *args, **kwargs)

    @staticmethod
    def sNew(sdTypeEnumId):
        """
        Create a new SDTypeEnum from the specified name

        :param sdTypeEnumId: The name of the SDTypeEnum type to retrieve
        :type sdTypeEnumId: string
        :rtype: SDTypeEnum
        """
        outSDTypeEnum = ctypes.c_void_p()
        _res = sd.getContext().SDTypeEnum_sNew(ctypes.create_string_buffer(sdTypeEnumId.encode('utf-8')), ctypes.byref(outSDTypeEnum))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = sd.getContext().mTypeMap[SDAPIObject(sd.getContext(), outSDTypeEnum, ownHandle=False).getClassName()]
        return constructor(sd.getContext(), outSDTypeEnum.value, ownHandle=True)

    def getEnumerators(self):
        """
        Get the available enumerators

        :rtype: SDArray[SDProperty]
        """
        outProperties = ctypes.c_void_p()
        _res = self.mAPIContext.SDTypeEnum_getEnumerators(self.mHandle, ctypes.byref(outProperties))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = self.mAPIContext.mTypeMap[SDAPIObject(self.mAPIContext, outProperties, ownHandle=False).getClassName()]
        return constructor(self.mAPIContext, outProperties.value, ownHandle=True)

