# ADOBE CONFIDENTIAL
#
# Copyright 2020 Adobe
# All Rights Reserved.
#
# NOTICE:  Adobe permits you to use, modify, and distribute this file in
# accordance with the terms of the Adobe license agreement accompanying it.
# If you have received this file from a source other than Adobe,
# then your use, modification, or distribution of it requires the prior
# written permission of Adobe.
#
# Autogenerated by ipa. Don't edit directly, edit the definitions and regenerate it when changing
#

import ctypes
import base64
import sd
from .sdvaluevector import *
from .sdapiobject import *
from .sdbasetypes import *
from .sdapiobject import *
from .apiexception import APIException

class SDValueBool4(SDValueVector):
    def __init__(self, APIContext, handle, *args, **kwargs):
        """
        Constructor

        :rtype: SDValueBool4
        """
        SDValueVector.__init__(self, APIContext, handle, *args, **kwargs)

    @staticmethod
    def sNew(value):
        """
        Create new SDValueBool4

        :param value: The name of the enum type
        :type value: bool4
        :rtype: SDValueBool4
        """
        outSDValueBool4 = ctypes.c_void_p()
        _res = sd.getContext().SDValueBool4_sNew(ctypes.byref(value), ctypes.byref(outSDValueBool4))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        constructor = sd.getContext().mTypeMap[SDAPIObject(sd.getContext(), outSDValueBool4, ownHandle=False).getClassName()]
        return constructor(sd.getContext(), outSDValueBool4.value, ownHandle=True)

    def get(self):
        """
        Get the base type value as bool4

        :rtype: bool4
        """
        outValue = bool4()
        _res = self.mAPIContext.SDValueBool4_get(self.mHandle, ctypes.byref(outValue))
        if _res != SDApiError.NoError.value:
            if _res == SDApiError.NoErrorOutputParamNotSet.value:
                return None
            raise APIException(SDApiError(_res))
        return outValue

